export enum HistorialEntidad {
  PEDIDO = "PEDIDO",
  LOTE = "LOTE",
  LOTE_TOSTADO = "LOTE_TOSTADO",
  MUESTRA = "MUESTRA",
  INSUMO = "INSUMO",
  BOLSA = 'BOLSA',
  PRODUCTO = "PRODUCTO",
  INVENTARIO = "INVENTARIO",
  TUESTE = "TUESTE",
  PAQUETE = "PAQUETE",
  ENVIO = "ENVIO",
}