export class CreateAnalisisRapidoDto {
  constructor(
    public fragancia: string,
    public aroma: string,
    public floral: boolean,
    public afrutado: boolean,
    public bayas: boolean,
    public frutos_secos: boolean,
    public citricos: boolean,
    public acido_fermentado: boolean,
    public acido: boolean,
    public fermentado: boolean,
    public verde_vegetal: boolean,
    public otros: boolean,
    public quimico: boolean,
    public rancio: boolean,
    public tierra: boolean,
    public papel: boolean,
    public tostado: boolean,
    public nueces_cacao: boolean,
    public nueces: boolean,
    public cocoa: boolean,
    public especias: boolean,
    public dulce: boolean,
    public vainilla: boolean,
    public azucar_morena: boolean,
    public comentario?: string,
  ) {}

  static create(props: { [key: string]: any }): [string?, CreateAnalisisRapidoDto?] {
    const {
      fragancia,
      aroma,
      floral,
      afrutado,
      bayas,
      frutos_secos,
      citricos,
      acido_fermentado,
      acido,
      fermentado,
      verde_vegetal,
      otros,
      quimico,
      rancio,
      tierra,
      papel,
      tostado,
      nueces_cacao,
      nueces,
      cocoa,
      especias,
      dulce,
      vainilla,
      azucar_morena,
      comentario,
    } = props;

    if(fragancia === undefined || aroma === undefined) {
      return ["Fragancia y aroma son obligatorios"];
    }
    

    return [
      undefined,
      new CreateAnalisisRapidoDto(
        fragancia,
        aroma,
        floral,
        afrutado,
        bayas,
        frutos_secos,
        citricos,
        acido_fermentado,
        acido,
        fermentado,
        verde_vegetal,
        otros,
        quimico,
        rancio,
        tierra,
        papel,
        tostado,
        nueces_cacao,
        nueces,
        cocoa,
        especias,
        dulce,
        vainilla,
        azucar_morena,
        comentario,
      ),
    ];
  }
}