export interface Tueste {
    id_tueste: string;
    id_lote: string;
    fecha_tueste: Date;
    tostadora: string;
    cliente: string;
    productor: string;
    densidad: number;
    humedad: number;
    peso_entrada: number;
    tipo_tueste: string;
    temperatura_entrada: number;
    llama_inicial: number;
    aire_inicial: number;
    punto_no_retorno: string;
    tiempo_despues_crack: string;
    temperatura_crack: number;
    temperatura_salida: number;
    tiempo_total: string;
    porcentaje_caramelizacion: number;
    desarrollo: number;
    grados_desarrollo: number;
    peso_salida: number;
    merma: number;
    agtrom_comercial: number;
    agtrom_gurme: number;
    id_usuario?: string;
    id_pedido?: string;
}